package:
  name: pyswark
  version: 0.0.0

about:
  author : pyt3r
  license_file: LICENSE
  summary: a template python package

source:
  path: ..

build:
  noarch: python
  entry_points:
    - template-entry-point = pyswark.scripts.hello:world

requirements:
  build:
    - python=3.9
    - pyyaml
    - numpy
    - pydantic

  run:
    - python
    - pyyaml
    - coverage
