package:
  name: pyswark
  version: 0.0.3

about:
  author : pyt3r
  license_file: LICENSE
  summary: python swiss army knife

source:
  path: ..

build:
  noarch: python
  entry_points:
    - pyswark-entry-point = pyswark.scripts.hello:world

requirements:
  channels:
    - defaults
    - conda-forge
  build:
    - python>=3.9
    - pyyaml
    - numpy
    - pandas
    - pyarrow
    - pydantic
    - fsspec
    - requests
    - aiohttp
    - aenum
    - sqlalchemy
    - holoviews
    - panel
    - bokeh
    - jupyter_bokeh

  run:
    - python>=3.9
    - pyyaml
    - coverage
