package:
  name: pyswark
  version: 0.0.1

about:
  author : pyt3r
  license_file: LICENSE
  summary: python swiss army knife

source:
  path: ..

build:
  noarch: python
  entry_points:
    - pyswark-entry-point = pyswark.scripts.hello:world

requirements:
  build:
    - python>=3.9
    - pyyaml
    - numpy
    - pandas
    - pydantic
    - fsspec
    - requests

  run:
    - python>=3.9
    - pyyaml
    - coverage
